namespace: cf-registration
stacker_bucket_region: us-west-2
sys_path: ./

stacks:
  - name: shared
    class_path: shared.Registration
    variables:
      env-dict:
        BucketName: registration-shared-bucket

  - name: api
    class_path: api.Registration
    variables:
        env-dict:
          ApiName: registration-api-gateway

  - name: lambda
    class_path: lambda.Registartion
    variables:
        env-dict:
          BucketName: registration-shared-bucket
          RegistrationLambdaName: registration-lambda
          SharedSecretsId: trimana/dashboard/shared/secrets
